### ISSUE TITLE
Not clear how to use the cmsis-svd-data git?

### ISSUE THREAD

**Issue by zkrx** [cmsis-svd/cmsis-svd#186]
Since you removed the data/ folder and moved it into its own repo, things that depended on it broke. See this comment that I just made on the AUR for details:
https://aur.archlinux.org/packages/cmsis-svd-git#comment-953114

I think the README should provide clear information on how to retrieve and use the data/ folder.

Thanks

**Comment by BenBE** [comment]
See the changes introduced in #180:
You need to provide a `package_root` directory to [`SVDParser.for_packaged_svd`](https://github.com/cmsis-svd/cmsis-svd/blob/56b924806e634df89e7140328a45b8900fd19d86/python/cmsis_svd/parser.py#L308-L320) or [`SVDParser.for_packaged_mcu`](https://github.com/cmsis-svd/cmsis-svd/blob/56b924806e634df89e7140328a45b8900fd19d86/python/cmsis_svd/parser.py#L335-L358). Have a look at the [examples](https://github.com/cmsis-svd/cmsis-svd/blob/56b924806e634df89e7140328a45b8900fd19d86/python/cmsis_svd/examples/show_k20_peripherals.py#L19-L25) provided for this project.

**Comment by zkrx** [comment]
Thanks for the help.

Sorry, I'm not sure I understand. I'm trying to have the following gist to work again:
https://gist.github.com/devanlai/644910b712361e7317ec2305884aea8d#file-svd-dump-py

In particular, this fails:
```
class SVDSelector(gdb.Command):
    def __init__(self):
        super(SVDSelector, self).__init__("svd_load", gdb.COMMAND_USER)
        vendor_names = pkg_resources.resource_listdir("cmsis_svd", "data")
        self.vendors = {}
        for vendor in vendor_names:
            fnames = pkg_resources.resource_listdir("cmsis_svd", "data/%s" % vendor)
            self.vendors[vendor] = [fname for fname in fnames if fname.lower().endswith(".svd")]
```
```
Traceback (most recent call last):
  File "/home/user/svd-dump.py", line 266, in <module>
    SVDSelector()
  File "/home/user/svd-dump.py", line 70, in __init__
    vendor_names = pkg_resources.resource_listdir("cmsis_svd", "data")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1231, in resource_listdir
    return get_provider(package_or_requirement).resource_listdir(resource_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1538, in resource_listdir
    return self._listdir(self._fn(self.module_path, resource_name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1721, in _listdir
    return os.listdir(path)
           ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.11/site-packages/cmsis_svd/data'
```

I can't find the data/ folder any longer.

**Comment by BenBE** [comment]
Instead of iterating the directory of the `pkg_resources` you will need to list the contents of a directory provided externally.

Assuming you had some function `get_svd_path()` that read an environment variable (cf. example I linked), you'd fetch that directory and read the list of files with e.g. `opendir`/`readdir`/`closedir`. Similar for the vendor subdirectories.

For this to work you will have to clone the [`cmsis-svd-data` repository](https://github.com/cmsis-svd/cmsis-svd-data/) and point your script to the data directory in there (e.g. with an environment variable or some other configuration.

If you cloned said repo to `/var/lib/cmsis-svd-data` you'd configure the base path to be something like `/var/lib/cmsis-svd-data/data`. For the two functions I mentioned above, you simple provide this path in the first argument. Most of the changes to your gist are related to listing vendors and MCUs as that's not part of the public API in cmsis-svd AFAICS rn; thus that part has to be done by hand.

**Comment by zkrx** [comment]
Wow, this is really more help than I would have hoped for. Thanks a lot.

I was a bit surprised as I would have expected the `cmsis-svd-data` repo to be a submodule, or to be pulled during setup.py.

> the new git remote URL for this repository is

yes, somehow the old URL redirects to the current one. I agree it should be updated.

> more explicit information on how to use a data folder with the cmsis-svd library will be add.

I think it would be nice to have a quick mention in the README.

Perhaps the best course of action regarding the AUR is to have a 2nd cmsis-svd-data package and mark it as an (optional?) dependency. But I understand this is out of your scope.

I might try to fix the script and improve the AUR if I get the opportunity (this gdb script has been very handy for debugging), although time is lacking as always.

Again, thank you both for your time.

**Comment by zkrx** [comment]
Sorry, I closed the ticket by mistake. I'll let you handle that.
